steps:

# Using dep container from github.com/solo-io/cloud-builders/dep
# This copies files into the proper workspace layout and so must be run before other tasks
# Subsequent steps should set GOPATH variable to avoid setting up unnecessary sym link
- name: 'gcr.io/$PROJECT_ID/dep'
  args: ['ensure']
  env: ['PROJECT_ROOT=github.com/solo-io/go-utils']
  id: 'dep'

# Setup AWS credentials
- name: gcr.io/cloud-builders/gcloud
  args:
    - kms
    - decrypt
    - --ciphertext-file=./gopath/src/github.com/solo-io/go-utils/ci/aws_credentials.enc
    - --plaintext-file=/workspace/aws_credentials
    - --location=global
    - --keyring=build
    - --key=build-key
  waitFor: ['dep']
  id: 'setup-aws-creds'


# e2e-ginkgo is produced from https://github.com/solo-io/cloud-builders/e2e-ginkgo
# sets up redis, consul, kubectl, go with required environment variables
# need to use the provided entrypoint
- name: 'gcr.io/$PROJECT_ID/e2e-ginkgo'
  dir: './gopath/src/github.com/solo-io/go-utils'
  env:
    - 'PROJECT_ROOT=github.com/solo-io/go-utils'
    - 'RUN_KUBE_TESTS=1'
    - 'GOPATH=/workspace/gopath'
    - 'AWS_SHARED_CREDENTIALS_FILE=/workspace/aws_credentials'
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=test-cluster'
  args: ['-r']
  waitFor: ['dep', 'setup-aws-creds']
